name: UI/UX
favicon: null
layout_spectrum: 0.3317524634767324
typography_spectrum: 0.5680605191737413
title: Pixels on Canvas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdbdb'
    - '#b2aaa7'
    - '#46474c'
    - '#fcfcfc'
    - '#777576'
  brandStrength: 0.1875
  lightness: 0.9557001010980457
  saturation: 0.125
  rhythmicContrast: 0.19521883642300963
purpose: []
